server:
  port: ${SERVER_PORT_MENU:8080}
spring:
  application:
    name: "menu-service"

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/beef}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*" # Mở endpoint 'beans' và 'health'