apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: beef-restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostAliases:
        - ip: "192.168.1.33"
          hostnames:
            - "beef-api.trungkienit.cloud"
            - "beef-auth.trungkienit.cloud"
            - "api.beef.local"
            - "auth.beef.local"
            - "app.beef.local"
            - "admin.beef.local"
      containers:
        - name: frontend
          image: minh28012004/frontend:latest
          ports:
            - containerPort: 3000
          env:
            # Runtime variables (Next.js server-side)
            - name: NEXT_PUBLIC_API_BASE
              value: "https://beef-api.trungkienit.cloud"
            - name: NEXTAUTH_URL
              value: "https://beef.trungkienit.cloud"
            - name: KEYCLOAK_ISSUER
              value: "https://beef-auth.trungkienit.cloud/realms/master"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: beef-secrets
                  key: keycloak-client-secret-frontend
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: beef-secrets
                  key: nextauth-secret
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: INTERNAL_API_BASE_URL
              value: "http://gateway-service:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: beef-restaurant
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
