# docker-compose.yml
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      # Port cho AMQP protocol (để Spring Boot kết nối)
      - "5672:5672"
      # Port cho giao diện quản lý (truy cập bằng trình duyệt)
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
