server:
  port: ${SERVER_PORT_USER}
  servlet:
    context-path: /

spring:
  application:
    name: "user-service"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      path: ${H2_CONSOLE_PATH}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        dialect: ${JPA_DIALECT}

  flyway:
    enabled: ${FLYWAY_ENABLED}
    locations: ${FLYWAY_LOCATIONS}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}
            required: ${MAIL_SMTP_STARTTLS_REQUIRED}
          ssl.protocols: ${MAIL_SMTP_SSL_PROTOCOLS}
          connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT}
          timeout: ${MAIL_SMTP_TIMEOUT}
          writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_ID}

# Actuator & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS}

