apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: beef-restaurant
data:
  init_db.sql: |
    CREATE DATABASE userdb;
    CREATE DATABASE menudb;
    CREATE DATABASE orderingdb;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: beef-restaurant
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keycloak # Default DB
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beef-secrets
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: beef-restaurant
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
