apiVersion: v1
kind: Secret
metadata:
  name: beef-secrets
  namespace: beef-restaurant
type: Opaque
stringData:
  # PayOS (Payment Service)
  payos-client-id: "837f93ad-5c2b-410f-aa51-b963253131c6"
  payos-api-key: "21bf9186-9aed-44c7-8e98-c5cea9f4d9fd"
  payos-checksum-key: "b4f347435874a4de13900fcab97995ea81d465357e67d4c730ff248834457113"
  
  # Mail & User Service
  mail-password: "xjmb ajoe nxcw nzad"
  
  # Keycloak Backend Client
  keycloak-client-secret-backend: "QjBR6slVctGPSOOiSGZLMRAp5JGH96Wu"
  
  # Keycloak Frontend Client
  keycloak-client-secret-frontend: "r4QjsqNDIdCG41GvdNCEP4Sxe8T0RcJj"
  
  # NextAuth
  nextauth-secret: "your-nextauth-secret"
  
  # Common
  postgres-password: "keycloak"
  rabbitmq-password: "guest"
