server:
  port: ${SERVER_PORT_PAYMENT}

spring:
  application:
    name: "payment-service"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}
  fe-cancel-url: ${PAYOS_FE_CANCEL_URL}
  
eureka:
  client:
    fetchRegistry: ${EUREKA_FETCH_REGISTRY}
    registerWithEureka: ${EUREKA_REGISTER_WITH_EUREKA}
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_ID}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS}
