server:
  port: ${SERVER_PORT_PAYMENT:8083}
spring:
  application:
    name: "payment-service"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/master}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}

  return-url: "${FRONTEND_URL:http://localhost:3000}/payment-success"
  cancel-url: "${GATEWAY_URL:http://localhost:9000}/api/payment/cancel"
  fe-cancel-url: "${FRONTEND_URL:http://localhost:3000}/payment-cancel"
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}