spring:
  application:
    name: "discovery-service"

server:
  port: ${SERVER_PORT_DISCOVERY}

eureka:
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}
    eviction-interval-timer-in-ms: ${EUREKA_SERVER_EVICTION_INTERVAL}
    renewal-percent-threshold: ${EUREKA_SERVER_RENEWAL_PERCENT_THRESHOLD}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS}
